# This file is generated by Consul-Terraform-Sync.
#
# The HCL blocks, arguments, variables, and values are derived from the
# operator configuration for Consul-Terraform-Sync. Any manual changes to
# this file may not be preserved and could be overwritten by a subsequent
# update.
#
# Task: zpa_application_segment_update
# Description: This task dynamically updates application segments domain names, tcp and udp ports

services = {
  # "nginx.ip-10-0-0-114.dc1" = {
  #   id              = "216196257331309743"
  #   name            = "nginx"
  #   kind            = ""
  #   address         = "10.0.0.114"
  #   port            = 80
  #   meta            = {}
  #   tags            = []
  #   namespace       = ""
  #   status          = "passing"
  #   node            = "ip-10-0-0-114"
  #   node_id         = "9f39068d-94a3-2d66-5773-2f8246958cbe"
  #   node_address    = "10.0.0.114"
  #   node_datacenter = "dc1"
  #   node_tagged_addresses = {
  #     lan      = "10.0.0.114"
  #     lan_ipv4 = "10.0.0.114"
  #     wan      = "10.0.0.114"
  #     wan_ipv4 = "10.0.0.114"
  #   }
  #   node_meta = {
  #     consul-network-segment = ""
  #   }
  #   cts_user_defined_meta = {}
  # },
  # "nginx.ip-10-0-0-12.dc1" = {
  #   id              = "216196257331309747"
  #   name            = "nginx"
  #   kind            = ""
  #   address         = "10.0.0.12"
  #   port            = 80
  #   meta            = {}
  #   tags            = []
  #   namespace       = ""
  #   status          = "passing"
  #   node            = "ip-10-0-0-12"
  #   node_id         = "9280b5be-9a3a-623e-d6e8-af77998255d2"
  #   node_address    = "10.0.0.12"
  #   node_datacenter = "dc1"
  #   node_tagged_addresses = {
  #     lan      = "10.0.0.12"
  #     lan_ipv4 = "10.0.0.12"
  #     wan      = "10.0.0.12"
  #     wan_ipv4 = "10.0.0.12"
  #   }
  #   node_meta = {
  #     consul-network-segment = ""
  #   }
  #   cts_user_defined_meta = {}
  # },
  "nginx.ip-10-0-0-127.dc1" = {
    id              = "216196257331309744"
    name            = "nginx"
    kind            = ""
    address         = "10.0.0.127"
    port            = 80
    meta            = {}
    tags            = []
    namespace       = ""
    status          = "passing"
    node            = "ip-10-0-0-127"
    node_id         = "043abbdf-b1a7-fd6f-4d0f-28d6c932057c"
    node_address    = "10.0.0.127"
    node_datacenter = "dc1"
    node_tagged_addresses = {
      lan      = "10.0.0.127"
      lan_ipv4 = "10.0.0.127"
      wan      = "10.0.0.127"
      wan_ipv4 = "10.0.0.127"
    }
    node_meta = {
      consul-network-segment = ""
    }
    cts_user_defined_meta = {}
  },
  "nginx.ip-10-0-0-13.dc1" = {
    id              = "216196257331309726"
    name            = "nginx"
    kind            = ""
    address         = "10.0.0.13"
    port            = 80
    meta            = {}
    tags            = []
    namespace       = ""
    status          = "passing"
    node            = "ip-10-0-0-13"
    node_id         = "0d335114-1cb3-8372-0d46-f888f748e5ed"
    node_address    = "10.0.0.13"
    node_datacenter = "dc1"
    node_tagged_addresses = {
      lan      = "10.0.0.13"
      lan_ipv4 = "10.0.0.13"
      wan      = "10.0.0.13"
      wan_ipv4 = "10.0.0.13"
    }
    node_meta = {
      consul-network-segment = ""
    }
    cts_user_defined_meta = {}
  },
  "nginx.ip-10-0-0-213.dc1" = {
    id              = "216196257331309741"
    name            = "nginx"
    kind            = ""
    address         = "10.0.0.213"
    port            = 80
    meta            = {}
    tags            = []
    namespace       = ""
    status          = "passing"
    node            = "ip-10-0-0-213"
    node_id         = "945b011a-5cc7-a4d7-08c2-39620c37536c"
    node_address    = "10.0.0.213"
    node_datacenter = "dc1"
    node_tagged_addresses = {
      lan      = "10.0.0.213"
      lan_ipv4 = "10.0.0.213"
      wan      = "10.0.0.213"
      wan_ipv4 = "10.0.0.213"
    }
    node_meta = {
      consul-network-segment = ""
    }
    cts_user_defined_meta = {}
  },
  "nginx.ip-10-0-0-91.dc1" = {
    id              = "216196257331309745"
    name            = "nginx"
    kind            = ""
    address         = "10.0.0.91"
    port            = 80
    meta            = {}
    tags            = []
    namespace       = ""
    status          = "passing"
    node            = "ip-10-0-0-91"
    node_id         = "fe3c85d3-4c35-4f64-7758-d3c16bde2794"
    node_address    = "10.0.0.91"
    node_datacenter = "dc1"
    node_tagged_addresses = {
      lan      = "10.0.0.91"
      lan_ipv4 = "10.0.0.91"
      wan      = "10.0.0.91"
      wan_ipv4 = "10.0.0.91"
    }
    node_meta = {
      consul-network-segment = ""
    }
    cts_user_defined_meta = {}
  },
}